on:
  create:
    tags:
      - 'v*-react-native'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: |
          PACKAGE_VERSION="${GITHUB_REF##*/v}"
          PACKAGE_VERSION="${PACKAGE_VERSION%-react-native}"
          sed -i -e "0,/{/ s/{/{\n\t\"version\": \"${PACKAGE_VERSION}\",/" package.json
      - run: echo package.json
      - run: npm install
      - run: tsc index
      - run: npm run build
      - run: rm -r .github
      - run: rm nodemon.json .gitignore .prettierrc index.js
      - run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - run: npm whoami
      - run: npm publish --access public
