on:
  create:
    tags:
      - 'v*-react-native'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: |
          PACKAGE_VERSION="${GITHUB_REF#v}"
          PACKAGE_VERSION="${PACKAGE_VERSION%-react-native}"
          echo "${PACKAGE_VERSION}"
          exit 1
          sed -i -e "0,/{/ s/{/{\n\t\"version\": \"${PACKAGE_VERSION}\",/" package.json
          cat package.json
          exit 1
      - run: echo package.json
      - run: npm install
      - run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - run: npm whoami
      - run: npm publish --access public
